### ISSUE TITLE
Network configuration of VNET jails incorrect after reboot

### ISSUE THREAD

**Issue by Peter2121** [cbsd/cbsd#695] opened 2022-03-30 08:36 UTC
FreeBSD version ( uname -a ): 
13.0-RELEASE-p6

CBSD version ( cbsd version ): 
13.0.24

I have several VNET jails on the host. If I start (or restart) the jails manually - everything works fine. If I configure the jails to start automatically on boot - the network configuration is not applied correctly (even if parallel=0). 

For example, after reboot of the host:

On host I see both `epair7a` and `epair7b` interfaces:

```
epair7a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        description: rproxy6-eth0
        options=8<VLAN_MTU>
        ether 02:2b:73:67:76:0a
        inet 10.192.6.7 netmask 0xffffff00 broadcast 10.192.6.255
        groups: epair
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
epair7b: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=8<VLAN_MTU>
        ether 00:a0:98:e5:25:88
        hwaddr 02:2b:73:67:76:0b
        groups: epair
        media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
        status: active
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```

In jail I see only `lo0` interface:

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
```

Normally `epair7b` should become `eth0` in jail and have the address 10.192.6.137. It should disappear from host configuration.

**Comment by lnxsrt** [comment] 2022-04-11 01:36
I'm also having issues on reboot or restart of vnet jails. But, mine do have eth0 interface in the jail. The issue is that the rc.conf output from CBSD doesn't put the ifconfig_eth0 line in the correct order. 

CBSD generates this...
`ifconfig_eth0="192.168.1.28/24 inet up"`

It should have generated this...
`ifconfig_eth0="inet 192.168.1.28/24 up"`

**Comment by olevole** [comment] 2022-04-11 18:14
Most likely this is a race condition with parallel search and creation of `epair` pairs. In the latest CBSD version (13.0.28), `boot_delay` should affect this problem (this is work-around, not a solution of the problem). Please check **boot_delay** settings in CBSD >= 13.0.28:

```
cbsd jls display=jname,astart,boot_delay
```

When boot_delay=0, jails(and bhyve)  will automatically start with an incremental delay - nothing to do and your problem should be fixed. If the values are the same ( and != **0** ), try manually setting the delays, for example:

```
#!/bin/sh

seq=0

for i in $( cbsd jorder ); do
       seq=$(( seq + 1 ))
       cbsd jset jname=${i} boot_delay=${seq}
done

# check result:
cbsd jls display=jname,astart,boot_delay

```

but diagnosing and fixing the real problem will take some time

**Comment by olevole** [comment] 2022-06-20 09:51
@Peter2121 the problem was in incorrect blocking when starting an interface search at the same time.

Please reopen this issue if the bug still relevant for **13.1.1**+

My test:

1) `check.sh`:
```
#!/bin/sh
A=$( cbsd get-next-nic name=epair )
echo $A
```
2) `test.sh`:
```
#!/bin/sh
./check.sh &
./check.sh &
```

3) `./test.sh`:
```
# ./test.sh
epair1
epair2

# ./test.sh
epair3
epair4
...
```

**Closed as completed by olevole** 2022-06-20 09:51 UTC

**Comment by Peter2121** [comment] 2022-06-20 10:11
Very good news, thanks a lot!
