### ISSUE TITLE
cbsd is creating tmux sessions in the wrong directory when an Ubuntu chroot is present

### ISSUE THREAD

**Issue by PaddyMac** [cbsd/cbsd#528] opened 2020-10-04 14:49 UTC
FreeBSD version ( uname -a ): 13.0-CURRENT #3 88d21a5afef-c271973(master)

CBSD version ( cbsd version ): 12.1.16

I have an Ubuntu chroot set up per https://wiki.freebsd.org/LinuxJails. I had an issue where a deleted bhyve instance created by cbsd left traces that I was trying to find and remove, and this led me to discover that the tmux instances that cbsd was creating were in the wrong location. For some reason cbsd was creating them in /compat/ubuntu/tmp/tmux-0/ . I checked, and I don't have tmux installed inside the Ubuntu chroot, so that wasn't the cause. Maybe something about my environment caused it to choose this directory. In any case, even after the bhyve VM was removed with "cbsd bremove", it left behind those files.

I also noticed that tmux files were also creted in /tmp/tmux-0/ where I would expect them to be. So for some reason multiple copies are being created.

Actually, the more I think about it, I wonder if this is a bug or if it should do this if the root user on the FreeBSD system chroots into the Ubuntu installation. What do you think?

**Comment by olevole** [comment] 2020-10-04 15:34
Very interesting. I can assume that tmux can use environment variables like TMPDIR and this value in your case was reassigned when Linux jail was created/started. But that's just theory. Am I getting it right that you cannot reproduce this?

**Comment by PaddyMac** [comment] 2020-10-08 17:58
I'll probably have some time over the weekend to try out some things and figure out exactly when it happens. My guess is that it probably happens when I execute "chroot /compat/ubuntu /bin/bash" from a root prompt. So I do think it's reproducible.

**Comment by olevole** [comment] 2021-01-06 10:30
no response

**Closed by olevole** 2021-01-06 10:30 UTC
