### ISSUE TITLE
fstab.jailname.local only operates on first entry (zfs)

### ISSUE THREAD

**Issue by uropro** [cbsd/cbsd#241] opened 2018-01-24 14:43 UTC
fstab.`jailname`.local is intended for additional mounting of file systems. 

I have two entries for a zfs file system. Only the first entry is processed (and also works). The second is silently ignored.

FreeBSD version ( uname -a ): 11.1
CBSD version ( cbsd version ): 11.1.13

/usr/jails/jails-fstab/fstab.sambajail.local contains the following line

    # additional mappings for sambajail
    #
    zdisk/samba /root/zdisk zfs rw 0 0
    zssd/samba /root/zssd zfs rw 0 0

**Comment by olevole** [comment] 2018-01-24 15:03
**Notes for myself**:

Looks like zfs(attach)-only bug, due to in UFS multiple records with other FS-type works, e.g:
~~~
/bin /tmp/bin nullfs ro 0 0
/sbin /tmp/sbin nullfs ro 0 0
tmpfs /tmp/tmpfs tmpfs rw 0 0
~~~

**Comment by uropro** [comment] 2018-01-24 17:12
The problem is in the tools/attachzfs script:
The sub-routine `mount_via_fstab` iterates over the contents of the file `${fstab}`, but stops upon the first occurrence of a zfs-file system (_fs is zfs): after checking zfs_check_and_attach, there are returns which abandons the iteration over the fstab entries.

Another thing puzzles me: Why is `zfs_check_and_attached` called inside `mount_via_fstab` (which I understand)  but also at the end of the attachzfs-script?

Looks not so easy to fix...

**Comment by uropro** [comment] 2018-01-24 17:17
As a quick fix I have commented out the returns in the `mount_via_fstab` sub-routine and also the isolated call to `zfs_check_and_attach` and its return checking `case`. at the end of tools/attachzfs.
Now the two zfs filesystems get mounted!

**Comment by olevole** [comment] 2018-01-24 20:20
Yes, this is a logical error. Instead of `return X`, we must use `continue` to go to the next element. Thanks again for report, it's easy to fix ;-)

For some reason I do not like to use the `zfs attach` (I do not remember why this options frightened me ;). I think I've found some problems in FreeBSD in these places, for example i remember this: 

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=183986

Still there was a problem with `unjail` work, but I can not find my PR, maybe the problem was also fixed
Too few users (and developers) use it. So I prefer nullfs (with some loss of speed on locks operation and loss of functional zfs)

**Comment by olevole** [comment] 2018-01-24 20:28
This will be included in the next release. You can use:
~~~
fetch -o /usr/local/cbsd/tools/attachzfs https://raw.githubusercontent.com/cbsd/cbsd/master/tools/attachzfs
chmod +x /usr/local/cbsd/tools/attachzfs
cbsd initenv
~~~
To apply changes

**Comment by olevole** [comment] 2018-01-24 20:32
pls re-open if the problem is not resolved

**Closed by olevole** 2018-01-24 20:32 UTC
