### ISSUE TITLE
CBSD Node add Issues and Manual Emulation Copy inquiry on diff host|node.

### ISSUE THREAD

**Issue by JEAholding** [cbsd/cbsd#672] opened 2021-12-21 21:00 UTC
Mandatory info for bug reports:

FreeBSD version ( uname -a ): 
12.2-RELEASE-p3 FreeBSD 12.2-RELEASE-p3 GENERIC  amd64
13.0-RELEASE-p1

CBSD version ( cbsd version ): 
13.0.9
13.0.3

====================================================================================================
I have multiple versions of the CBSD and FREEBSD OS around multiple hosts/servers (the node section is a little confusing so I will ask some questions here)... 

Before I ask the questions regarding nodes function and rexe let's go-to basic... ASSUMING that node is broken or I can't get it to work etc... 

HOW do I manually clone the bhyve/emulated environment on another host? I look at the bhyvectl/bclone of the source and it seems that you're using Rsync.  

STEPS FOR MANUAL COPY in new HOST
1. Need to add new information in sqlite in the jails table or is this only for jails? Correct me if I am wrong or explain... 
2. Need to add new information in sqlite in the bhyve table ? Correct me if I am wrong or explain... 
Let me know if I am missing any other table in the sqlite source to CLONE a BHYVE manually on a new host. 

Repo/Folders

1. Clone/Create the jail-data/dir_of_bhyve (symlink pointing to vm folder)
2. Clone/Create the jail-system/dir_of_bhyve (symlink pointing to vm folder)
3. (CLONE the jails-fstab)= not needed it seems for virtio-9pfs
4. Clone/Create the vm/dir_of_bhyve

ZFS Files: 

1. ZFS send to duplicate the ZFS .vhd in new host. (Create the symlink in vm folder)
or
2. ZFS clone and pipe it to new host have vhd of clone (Create the symlink in vm folder)
or
3. ZFS create of the path (Copy vm and symlink)

Let me know if I am missing anything else required to do manual copying of bhyve or qemu or xen just trying to understand flow of all the necessary steps so that everything is routed and pointed correctly so I can just do cbsd bstart jname=dir_of_behyve in new host...

==========================================================================================================

Regarding cbsd node

cbsd node mode=add 

pw= password for CBSD user
Do I have to assign a password to CBSD? Do I do cbsd passwd and add one if it doesn't have? 
I assigned:
========passwd cbsd
========chown cbsd:cbsd /usr/jails/.ssh
========chown cbsd:cbsd /usr/jails/.rssh

port = an alternative number of sshd port. By default, nodes of CBSD use port 22222 for connection on SSH.
So this means I have to edit PF and add that port (22222)? Can I put the custom port of my SSHD instead? 
When I added 22222 to my PF gave output = failed to connect + connection problem (code 1)...
When I use my custom SSHD custom port stays in connecting to (NODE_IP) after 10-30 second output= Error + Connection problem (code1)

My SSHD settings does not have passwd we only connect via Authorized Keys how do I input that for the nodes? PAM in SSHD settings is set to NO also not sure if that might be an issue with cbsd. 

Can I create the keys and add to .rshh and .ssh ? 
ssh-keygen -t ed25519 -a 150 -P "passphrase" -C "name" -f /usr/jails/.ssh/id_ed25519_HOST1

ssh-keygen -t ed25519 -a 150 -P "passphrase" -C "name" -f /usr/jails/.rssh/id_ed25519_HOST2

How do I add nodes with keys when password prohibits in ssh? 
Any guidance or steps will be appreciated...

**Comment by olevole** [comment] 2021-12-22 05:25
Hi @JEAholding. Can you try the `cbsd zfs-migrator` script? Basic idea: bclone should choose (automatically or manually) the most suitable method, there are several cases:

1) ZFS discrete replication  ( zfs send / recv )
2) HammerFS
3) Custom script and/or storage-side implementation ( https://github.com/cbsd/cbsd/issues/672 + https://www.bsdstore.ru/en/12.0.x/wf_jclone_ssi.html#clone-local.d%20hook:%20local/custom%20data%20clone ) - for example we can use
storage capabilities.
4) rsync

`zfs-migrator` script requires for root access. But it should work as you expect - with ZFS snapshot.

I can answer the rest of the questions later. I'm sure we should write instruction for manual

**Comment by JEAholding** [comment] 2021-12-22 13:51
Ok, @olevole I will give it a try... The problem I see with this is HOW do I pass the keys? The workaround is to disable authorized keys in SSHD and I will also test by adding to .ssh/config file between hosts to see if that works... But still will need to include a passphrase not sure if I will need to add to the ssh-agent see if that works. 

Will test with zfs-migrator, rexe and CBSD node further without the restricted settings on SSHD...

**Comment by JEAholding** [comment] 2022-04-05 02:39
I'm back... 

I upgraded... 
cbsd --version 
13.0.26

==========================================================
Testing & CBSD config I performed. 

1.
I took off from /etc/ssh/sshd_config
1 (parameters) and it began to work... 

PasswordAuthentication yes

and it began to CONNECT... 

2.
cbsd node mode=add node=[REMOTE_LOCAL_IP] port=[REMOTE_LOCAL_PORT] 
Type cbsd Password
&
After connecting [ERROR]
/usr/jails/tmp/s10_local/cbsdsql:: unexpected operator
CBSD: Fetching inventory failed: s10_local
specify dst/src node via: node:path
specify dst/src node via: node:path


3.
cbsd node mode=list
NEW node STATUS= Disconnect
&
/usr/jails/tmp/s10_local/ = EMPTY


==========================================================
QUESTIONS & Possible Fixes: 

1.
How can I fix the error above with the nodes not getting the local.sqlite of the remote node? 

2.
I began messing playing with config file in /usr/jails/.ssh/config but it doesn't seem to function... What or how is this file use? 

3.
Why isn't cbsdsql command working in my box? Is this command depreciated? I do not see it anymore on cbsd --help. 

4.
Let me know if there is a new method of adding keys so I don't have to use CBSD user password to connect? Can I use pub key files now? I notice cbsd nodeaddkey and the cbsd sshkey in (cbsd --help) how do I use this you got any manual for it yet? 



Thanks in advance

**Comment by olevole** [comment] 2022-04-05 09:00
Hello. At the moment I can't test multi-node operations (temporary loss of infrastructure for development). 

If we talk about manual migration, then the virtual machine for CBSD is an entry in:

~cbsd/var/db/local.sqlite:
```
SELECT jname FROM jails WHERE emulator = "bhyve";
SELECT * FROM bhyve;
```

Everything else is in the ~cbsd/jails-data/**VM**-data directory   (disks or symlink to zvol ) and ~cbsd/jails-system/**VM**/  directory.

As you noted earlier, these directories are now symlinks when using the ZFS file system - this is by design so that all the data and disks of the virtual machine are in the same dataset, e.g:

```
% zfs list |grep cloudbsd
jails/cloudbsd1                                               2.85G   624G   404K  /usr/jails/vm/cloudbsd1
jails/cloudbsd1/dsk1.vhd                                      2.85G   624G  3.77G  -
```

So we can use the `-R` key for `zfs send` for recursive sending all `jails/cloudbsd1` data (with disks) to another host.

One of the method to transfer SQLite3 data for VM and register  on a new host is to run 'junregister':
```
cbsd junregister jname=cloudbsd1
cbsd bls
```

After junregister, all SQLite3 data from ~cbsd/var/db/local.sqlite will be in the file ~cbsd/jails-rcconf directory:

```
file -s ~cbsd/jails-rcconf/rc.conf_cloudbsd1 
```

You can copy this file on the new host in the same directory and register: `cbsd jregister cloudbsd1` or run `cbsd initenv`.

After that, you only need to transfer the dataset of the virtual machine.

Another way to copy only settings:

```
cbsd jexport jname=test jexport_exclude="/" 
```

Then move + jimport image on the new host.

This is if we are talking about manual migration.

Of course, the wrapper scripts (rclone, zfs-migrator, jcoldmigration ...) for this function need to be repaired.

I'm looking forward to bringing back some FreeBSD hosts for CBSD infrastructure to work on fixing bugs. These complex operations will definitely need to have [unit and regression tests](https://github.com/cbsd/cbsd/tree/develop/tests).

**Comment by almmos** [comment] 2022-10-11 12:47
> cbsd node mode=list
> NEW node STATUS= Disconnect

Hi all, first time here.

@JEAholding regarding your "Disconnect" problem.
Check on both node you want to be connected:
`ls -la ~cbsd/.ssh/ | grep socket`
It must be something ike this:
`drwx------   2 cbsd  cbsd    3 Oct  8 00:53 sockets`

I have had the same "Disconnect" problem for some reason - not proper ownership for socket folder - after an CBSD upgrade.
I have executed following command:
`chown cbsd:cbsd ~cbsd/.ssh/sockets`
Mode must be 700

Hope this help!

**Comment by olevole** [comment] 2022-10-11 13:27
yes - that could be one of the reasons, but the scripts should set the correct mode: https://github.com/cbsd/cbsd/blob/develop/misc/mtree#L17

**Comment by almmos** [comment] 2022-10-11 13:52
From what I can see, the script you have provided check for exist and set the mode.
My problem was related to ownership. Don't know why!

If I think a little more the `cbsd initenv` I use to run as root. So if for some reason the folder in question do not exists, it will be created by `mkdir -p ${cbsd_workdir}/.ssh/sockets` (line no 19) and the mode will be set 700 for it. But the owner will be root.

On the other hand, when ssh master connection command is invoked, it use the -l option for cbsd user and also cbsd user credentials. The socket owner will there be cbsd user and for this the sockets folder must be own by cbsd user.

I think a new line setting for this will help. There is some line at the end of the related file doing some ownership settings. Add one more somewhere there:
`chown cbsd:cbsd ${cbsd_workdir}/.ssh/sockets`

Thanks!

**Comment by olevole** [comment] 2022-12-18 16:29
I double-check permission for ~cbsd/.ssh dir and its ok (fresh CBSD 13.1.19 installation).
```
ls -la ~cbsd/ |grep ssh
drwx------   2 cbsd  cbsd      2 Dec 18 12:16 .rssh
drwx------   3 cbsd  cbsd      7 Dec 18 12:17 .ssh
```

Some information relative backup/DR (and manual copy for jail/VM data) was added at https://www.bsdstore.ru/en/cbsd_additional.html#hier

If you need re-generate host key, you can remove old ~cbsd/.ssh/* files and re-run `cbsd initenv`.

added notes about root key for `cbsd zfs-migrator` script: https://github.com/cbsd/cbsd/commit/ece0a62dce48560a152b0ae2ba9cb94be3dff16b

**Closed as completed by olevole** 2022-12-18 16:29 UTC
