### ISSUE TITLE
After upgrade can't start jails version 11.0.1

### ISSUE THREAD

**Issue by jnbek** [cbsd/cbsd#90] opened 2016-10-02 23:28 UTC
```
([J:0]root(1)@galatians5[/cbsd/jails]# cbsd jstart httpd                                                                                               [10/02/16][17:23:29])
Ip 192.168.0.128 already exists in LAN
NIC automatically selected: em0
Starting jail: httpd, parallel timeout=5
jail: httpd: unknown parameter: allow.mount.linsysfs
jail: httpd: unknown parameter: allow.mount.linprocfs
IPFW is not enabled
([J:0]root(1)@galatians5[/cbsd/jails]# cbsd jlogin httpd                                                                                               [10/02/16][17:23:42])
Not running
([J:0]root(1)@galatians5[/cbsd/jails]#
```

I just upgraded my ports packages, including cbsd, then after reboot, cbsd told me to run:
`cbsd initenv`
to upgrade the backend. But none of my jails now will start.

**Comment by olevole** [comment] 2016-10-03 07:05
whta version you are using as hoster? do to limited resources i check only latest releases and freebsd 11.

**Comment by olevole** [comment] 2016-10-03 08:48
As work-around, you can temporary disable 'allow_mount' options for your jail:

~~~
cbsd jconfig
~~~

and sets **allow_mount** to 0

https://lists.freebsd.org/pipermail/svn-src-stable-10/2016-February/008293.html

Looks like this options available only from 10.3-RELEASE++
Anyway, i want to know version of FreeBSD and disable this options for FreeBSD <10.3 if you have less than 10.3 version.

**Comment by olevole** [comment] 2016-10-03 19:38
Probably fixed in 11.0.2, send to ports: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213176

**Comment by jnbek** [comment] 2016-10-03 19:59
I will test it when I get home. I am running FreeBSD 10.2-Stable on the server. I upgraded all my ports, before proceeding with the OS upgrades, it had been quite a while since I'd updated the ports so, I fig'd I'd solve any ports problems, THEN upgrade the OS, I'll be source upgrading to 11-STABLE and want to minimize any issues.

**Comment by jnbek** [comment] 2016-10-04 22:28
The update fixed the problem. Thanks

**Comment by czkarex** [comment] 2016-10-05 17:37
After upgrade to 11.0.2 similar trouble (Actual FreeBSD ver. 11.0-RELEASE). Jail not start with allow_mount (1). With error: jail_set: Operation not permitted.
Any idea? Thanks, Karel

**Comment by olevole** [comment] 2016-10-05 21:32
@czkarex  Can you post full log from

~~~
cbsd jstart XXX
~~~

command? 
And also:

1)
~~~
% uname -a
~~~

2)
~~~
% file -s /bin/sh
~~~

3)
~~~
% cbsd -c ' cbsdsql local select * from jails ' |grep ^XXX
~~~
(where XXX - jail name)

Jail is starts if you set 'allow_mount' to 0 in 
~~~
% cbsd jconfig
~~~
?

**Comment by czkarex** [comment] 2016-10-05 21:54
1) cbsd jstart agnes
Ip 10.65.40.1 already exists in LAN
NIC automatically selected: em0
set resource limit: [ ]
Starting jail: agnes, parallel timeout=5
jail: agnes: jail_set: Operation not permitted
IPFW is not enabled

2) uname -a
FreeBSD maggie 11.0-RELEASE FreeBSD 11.0-RELEASE #5 r306684M: Tue Oct  4 22:48:39 CEST 2016     karel@maggie:/usr/obj/usr/src/sys/MAGGIEKERN  amd64

3) file -s /bin/sh
/bin/sh: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 11.0 (1100120), FreeBSD-style, stripped

4) cbsd -c ' cbsdsql local select * from jails ' |grep ^agnes
agnes|0|/usr/jails/jails/agnes|agnes.my.domain|10.65.40.1/24|1|1|1|1|/usr/jails/jails-fstab/fstab.agnes|1|5|auto|0|0|0|0|0|0|1|0|/usr/jails/jails-data/agnes-data|0|1|0|/usr/jails/jails-rcconf/rc.conf_agnes|1|11|amd64|0|/bin/sh /etc/rc|/bin/sh /etc/rc.shutdown|0|0|0|0|0|0|0|0|0|180|0|900|1|1|0|1|1|0|0|jail|0|0|1|0|10|0|new|0|0

5) allow_mount: 0
cbsd jstart agnes
Ip 10.65.40.1 already exists in LAN
NIC automatically selected: em0
set resource limit: [ ]
Starting jail: agnes, parallel timeout=5
agnes: created
IPFW is not enabled
it's work....

**Comment by olevole** [comment] 2016-10-06 10:54
@czkarex Still not very clear for me..

All difference on allow_mount in:
https://github.com/cbsd/cbsd/blob/master/tools/makejconf#L239

After @jnbek issue, i've added test (based on ELF header/version) for skipping features that absent on FreeBSD < 10.3:
~~~
if [ "${allow_mount}" = "1" ]; then
	echo "allow.mount = \"true\";" >> ${out}
	echo "enforce_statfs=\"1\";" >>${out}

	if [ ${freebsdhostversion} -gt 1003000 ]; then
		echo "allow.mount.linsysfs = \"true\";" >> ${out}
		echo "allow.mount.linprocfs=\"1\";" >> ${out}
	fi
fi
~~~

What return to you execution of:
~~~
sysctl -a | grep -E "linproc|linsys"
~~~

?

You can help me by debugging  which exactly allow\* params not working. To do this, create new jail with **baserw=1** (it need to skip nullfs mounts), e.g: jail1

Create jconf for this jail:
0)
~~~
% cbsd makejconf jname=jail1 out=/tmp/jconf.jconf
~~~

<< it generate standart jail.conf for the jail1 jail.

1) Run jail1 by jconf:
~~~
% jail -f /tmp/jconf.jconf -c jail1
~~~

2) Stop jail1 via CBSD:
~~~
% cbsd jstop jail1
~~~

You can remove by one line in /tmp/jconf.jconf *allow_* params in cycle stop/start (by repeating 1/2 steps) to find which parameter is causing the error.

It not reproduce on my FreeBSD 11 ;-(

**Comment by czkarex** [comment] 2016-10-06 14:32
I upgraded CBSD from 10.3 to 11.0.2. (FreeBSD 11 only update to actual release)
1) sysctl -a | grep -E "linproc|linsys"
security.jail.param.allow.mount.linsysfs: 0
security.jail.param.allow.mount.linprocfs: 0
security.jail.mount_linsysfs_allowed: 0
security.jail.mount_linprocfs_allowed: 0 

I tested it, result is: I have to set:
allow.mount.linsysfs = "false";
allow.mount.linprocfs="0";
Jail working,
And fails during stopping:
jail: jail1: mount.fdescfs: /usr/jails/jails-data/jail1-data/dev/fd: not a mount point

K.

**Comment by czkarex** [comment] 2016-10-14 18:32
Error is in my custom kernel. (modifications Xorg in jail) I use the modification by you (from ver. 10). Could you help me with it? Thanks, K.

**Comment by olevole** [comment] 2016-10-14 19:33
Now I understand why I have not reproduced ) I stopped using xorg-in-jail some time ago, so CBSD patch is not actual (or not tested this on FreeBSD 11.0-RELEASE).  What a patch you applied?

**Comment by czkarex** [comment] 2016-10-14 19:45
I'm using some version your patch (for FreeBSD ver. 10.1). It worked correctly to releng/11.0 (Before update to 11.0-RELEASE-p1).

**Comment by olevole** [comment] 2016-10-15 11:31
I just update and test patch for FreeBSD 11.0-RELEASE: https://github.com/cbsd/cbsd/commit/19b72148fba31e8ecd774b34db6f6f86672dc56d

If you build kernel with 'buildkernel' script, you need to change 

apply_cbsd_patch=0
to 
apply_cbsd_patch=1

in ~workdir/etc/scrup.conf 
and run:

~~~
cbsd srcup
~~~

**Closed by olevole** 2016-10-15 11:31 UTC

**Comment by czkarex** [comment] 2016-10-15 11:34
Error was in my update script, patch 11 is OK, fbfs patch isn't compatible. My mistake, sorry. K
