### ISSUE TITLE
default nice 1 prevents cron in jail

### ISSUE THREAD

**Issue by uropro** [cbsd/cbsd#437] opened 2019-10-01 08:06 UTC
In my setup, the RACCT limit of 'nice' was set to 1. This will prevent cron inside a jail to change its nice level and in turn fails and produces log entries in /var/log/cron such as:

Oct  1 09:15:09 anyjail /usr/sbin/cron[90647]: (root) CMD (   /usr/libexec/atrun)
Oct  1 09:15:09 anyjail cron[90647]: setpriority 'root' (daemon): Permission denied

Solution: Set nice to 0 in the jrctl - Rrtl config section of jconfig or jconstruct.
Or are there other solutions for ncie != 1 ?

FreeBSD version: 12.0-RELEASE-p10
CBSD version: 12.1.1_1

**Comment by uropro** [comment] 2019-10-01 08:14
ADDENDUM: In my setup, RACCT is not enabled. Further more, rctl has no property "nice", but in the jconfig tui, there is an entry.

**Comment by olevole** [comment] 2019-10-03 21:26
@uropro interesting observation. I did not take into account that jail can limit renice.
My logic is as follows - since CPU usage in jail/container or bhyve virtual machine can may affect host processes (which are important, for example sshd), I set default nice to '1' (a little bit less than most hoster process). see **etc/defaults/jail-freebsd-default.conf**: https://github.com/cbsd/cbsd/blob/v12.1.1/etc/defaults/jail-freebsd-default.conf#L121-L122

You can overwrite default settings via config files. Just put "**nice=0**" into **etc/jail-freebsd-default.conf**, e.g:

`echo 'nice=0' > ~cbsd/etc/jail-freebsd-default.conf`
or for bhyve
`echo 'nice=0' > ~cbsd/etc/bhyve-freebsd-default.conf`

or in runtime:

cbsd jset nice=0 jname='jail'

**Comment by olevole** [comment] 2019-10-03 21:31
**nice** settings are “grouped” into “RACCT” settings (because some restrictions apply), and this works even if kern.racct.enable = 0, because the settings work through nice / renice tools, not RACCT ;-)

**Comment by uropro** [comment] 2019-10-04 07:41
Thanks for the clarification!
BTW: Great work, thank you very much! CBSD works very nicely, at nice=0 ;-)

**Comment by olevole** [comment] 2019-10-05 09:41
Oops, just checked on myself.
Forgot to change after renaming **nice** to **rctl_nice** in config:

https://github.com/cbsd/cbsd/commit/587d7163cf1a6aa5b9509e65f73c317b11b31faa

^^ you need this line for the configuration files to work

it will be in the next CBSD release (after FreeBSD 12.1-RELEASE). Reopen if the problem still remains

**Closed by olevole** 2019-10-05 09:41 UTC

**Comment by bitcoin-software** [comment] 2021-11-21 13:02
On a fresh setup with fbsd 13.0+13.0.18 problem (is it a problem or misconfiguration?) still persists with defaults. Reproduced by setting up a fresh host with RACCT accounting disabled. Newly created jails have these log entries produced by atrun(8) every 5 minutes.

P.S. setting jail nice to 0 as suggested fixes this. but i am not sure when i should disable crons or set higher nice

**Comment by tm-up** [comment] 2021-11-21 13:45
I can confirm this behavior on 13.0+13.0.17 - I came across it only yesterday and was not yet 100% sure... I have both nice=0 and rctl_nice=0 set in my template, yet after creating a new jail the value 'nice' is set to 1. RACCT is disabled too.
And while at it: setting allow_fdescfs=0 does not work from within jconfig-tui and the template. Doing cbsd jset... works.
