### ISSUE TITLE
cbsd help results in segfault in 12.0.8

### ISSUE THREAD

**Issue by VVelox** [cbsd/cbsd#398] opened 2019-04-14 10:30 UTC
Mandatory info for bug reports:

FreeBSD version ( uname -a ):  FreeBSD nibbles.vulpes.vvelox.net 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64

FreeBSD vixen42.vulpes.vvelox.net 12.0-STABLE FreeBSD 12.0-STABLE r342883 vixen42  amd64

CBSD version ( cbsd version ):  12.0.8

The following happens on both 12.0 RELAESE and 12 STABLE.

```
[root@nibbles]139|/root>cbsd help
CBSD version:         12.0.8
CBSD documentation:   https://bsdstore.ru/en/docs.html
CBSD user group chat: https://web.telegram.org/#/im?p=%40cbsdofficial

Available commands:

pkg  --  [helpers] cbsd pkg wrapper
tzsetup  --  [bsdconf] cbsd tzsetup wrapper
ssh  --  [bsdconf] OpenSSH jail helper
ftp  --  [bsdconf] Install timezone helper
adduser  --  [sys] Add user to jail
passwd  --  [bsdconf] cbsd passwd wrapper
service  --  [bsdconf] cbsd service wrapper
sysrc  --  [bsdconf] cbsd sysrc wrapper
userlist  --  [sys] Show user list
grouplist  --  [sys] Show group list
adduser-tui  --  [bsdconf] Ncurses based dialog for jcreate
pw  --  [bsdconf] cbsd pw wrapper
cloudinit  --  [sys] cloud-init helper t generate CI yaml
zfsinstall  --  [helpers] mfsBSD ZFS install script
zsh: segmentation fault  cbsd help
```

**Comment by mekanix** [comment] 2019-04-14 10:31
Does it also happen with non-zsh shells?

**Comment by VVelox** [comment] 2019-04-14 10:34
@mekanix If I jump into csh, same thing happens. The zsh at the last part is just zsh reporting a fault.

The shell it is being ran under should really not affect it and in previous versions it use to work with out segfaulting.

```
[root@vixen42]/arc/src/ports# cbsd help
CBSD version:         12.0.8
CBSD documentation:   https://bsdstore.ru/en/docs.html
CBSD user group chat: https://web.telegram.org/#/im?p=%40cbsdofficial

Available commands:

pkg  --  [helpers] cbsd pkg wrapper
tzsetup  --  [bsdconf] cbsd tzsetup wrapper
ssh  --  [bsdconf] OpenSSH jail helper
ftp  --  [bsdconf] Install timezone helper
adduser  --  [sys] Add user to jail
passwd  --  [bsdconf] cbsd passwd wrapper
service  --  [bsdconf] cbsd service wrapper
sysrc  --  [bsdconf] cbsd sysrc wrapper
userlist  --  [sys] Show user list
grouplist  --  [sys] Show group list
adduser-tui  --  [bsdconf] Ncurses based dialog for jcreate
pw  --  [bsdconf] cbsd pw wrapper
cloudinit  --  [sys] cloud-init helper t generate CI yaml
zfsinstall  --  [helpers] mfsBSD ZFS install script
Segmentation fault
Exit 139
[root@vixen42]/arc/src/ports#

```

**Comment by mekanix** [comment] 2019-04-14 10:36
I totally agree, I just couldn't reproduce it. Now I can. Thanx!

**Comment by olevole** [comment] 2019-04-14 10:46
this is already fixed by https://github.com/cbsd/cbsd/commit/730bf6b76e361607f21f69efa8ec93a589abdd05
https://github.com/cbsd/cbsd/commit/b38f57c52424f75c8e580db4e233520c0d4b45c1

main line:

- . ${workdir}/securecmd
+ . ${distdir}/securecmd

This is due to the support of multiple workdir

**Comment by VVelox** [comment] 2019-04-14 10:58
Awesome! 730bf6b does definitely fix it.

Thanks! <3

**Closed** 2019-04-14 10:59 UTC
